/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import com.toedter.calendar.JDateChooser;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.sql.Date;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luciano
 */
public class EstadisticasGUI extends javax.swing.JPanel {
    
    private DefaultTableModel tablaEstDef;

    /**
     * Creates new form EstadisticasGUI
     */
    public EstadisticasGUI() {
        initComponents();
        tablaEstDef = (DefaultTableModel) tablaEst.getModel();
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tablaEstadisticas = new javax.swing.JScrollPane();
        tablaEst = new javax.swing.JTable();
        labelDia = new javax.swing.JLabel();
        labelDesde = new javax.swing.JLabel();
        labelHasta = new javax.swing.JLabel();
        campoDia = new javax.swing.JTextField();
        calendarioDesde = new com.toedter.calendar.JDateChooser();
        calendarioHasta = new com.toedter.calendar.JDateChooser();

        setPreferredSize(new java.awt.Dimension(903, 581));

        jPanel1.setBackground(new java.awt.Color(187, 239, 229));

        tablaEstadisticas.setBackground(new java.awt.Color(254, 254, 254));
        tablaEstadisticas.setName("Estadisticas"); // NOI18N

        tablaEst.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod.Producto", "Cant. vendidos", "Ganancia", "Perdida"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaEstadisticas.setViewportView(tablaEst);

        labelDia.setText("Dia");

        labelDesde.setText("Desde");

        labelHasta.setText("Hasta");

        campoDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDiaActionPerformed(evt);
            }
        });

        calendarioDesde.setDateFormatString("yyyy-MM-dd");

        calendarioHasta.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDesde)
                            .addComponent(labelHasta)
                            .addComponent(labelDia))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoDia, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calendarioDesde, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(calendarioHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tablaEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDia)
                    .addComponent(campoDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDesde)
                    .addComponent(calendarioDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelHasta)
                    .addComponent(calendarioHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(tablaEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(471, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDiaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser calendarioDesde;
    private com.toedter.calendar.JDateChooser calendarioHasta;
    private javax.swing.JTextField campoDia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDesde;
    private javax.swing.JLabel labelDia;
    private javax.swing.JLabel labelHasta;
    private javax.swing.JTable tablaEst;
    private javax.swing.JScrollPane tablaEstadisticas;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the calendarioDesde
     */
    public com.toedter.calendar.JDateChooser getCalendarioDesde() {
        return calendarioDesde;
    }

    /**
     * @param calendarioDesde the calendarioDesde to set
     */
    public void setCalendarioDesde(com.toedter.calendar.JDateChooser calendarioDesde) {
        this.calendarioDesde = calendarioDesde;
    }

    /**
     * @return the calendarioHasta
     */
    public com.toedter.calendar.JDateChooser getCalendarioHasta() {
        return calendarioHasta;
    }

    /**
     * @param calendarioHasta the calendarioHasta to set
     */
    public void setCalendarioHasta(com.toedter.calendar.JDateChooser calendarioHasta) {
        this.calendarioHasta = calendarioHasta;
    }

    /**
     * @return the campoDia
     */
    public javax.swing.JTextField getCampoDia() {
        return campoDia;
    }

    /**
     * @param campoDia the campoDia to set
     */
    public void setCampoDia(javax.swing.JTextField campoDia) {
        this.campoDia = campoDia;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * @return the labelDesde
     */
    public javax.swing.JLabel getLabelDesde() {
        return labelDesde;
    }

    /**
     * @param labelDesde the labelDesde to set
     */
    public void setLabelDesde(javax.swing.JLabel labelDesde) {
        this.labelDesde = labelDesde;
    }

    /**
     * @return the labelDia
     */
    public javax.swing.JLabel getLabelDia() {
        return labelDia;
    }

    /**
     * @param labelDia the labelDia to set
     */
    public void setLabelDia(javax.swing.JLabel labelDia) {
        this.labelDia = labelDia;
    }

    /**
     * @return the labelHasta
     */
    public javax.swing.JLabel getLabelHasta() {
        return labelHasta;
    }

    /**
     * @param labelHasta the labelHasta to set
     */
    public void setLabelHasta(javax.swing.JLabel labelHasta) {
        this.labelHasta = labelHasta;
    }

    /**
     * @return the tablaEst
     */
    public javax.swing.JTable getTablaEst() {
        return tablaEst;
    }

    /**
     * @param tablaEst the tablaEst to set
     */
    public void setTablaEst(javax.swing.JTable tablaEst) {
        this.tablaEst = tablaEst;
    }

    /**
     * @return the tablaEstadisticas
     */
    public javax.swing.JScrollPane getTablaEstadisticas() {
        return tablaEstadisticas;
    }

    /**
     * @param tablaEstadisticas the tablaEstadisticas to set
     */
    public void setTablaEstadisticas(javax.swing.JScrollPane tablaEstadisticas) {
        this.tablaEstadisticas = tablaEstadisticas;
    }

    /**
     * @return the tablaEstDef
     */
    public DefaultTableModel getTablaEstDef() {
        return tablaEstDef;
    }

    /**
     * @param tablaEstDef the tablaEstDef to set
     */
    public void setTablaEstDef(DefaultTableModel tablaEstDef) {
        this.tablaEstDef = tablaEstDef;
    }
}
