/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import com.toedter.calendar.JDateChooser;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.sql.Date;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luciano
 */
public class EstadisticasGUI extends javax.swing.JPanel {
    
    private DefaultTableModel tablaEstDef;

    /**
     * Creates new form EstadisticasGUI
     */
    public EstadisticasGUI() {
        initComponents();
        tablaEstDef = (DefaultTableModel) tablaEst.getModel();
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tablaEstadisticas = new javax.swing.JScrollPane();
        tablaEst = new javax.swing.JTable();
        labelDia = new javax.swing.JLabel();
        labelDesde = new javax.swing.JLabel();
        labelHasta = new javax.swing.JLabel();
        campoDia = new javax.swing.JTextField();
        calendarioDesde = new com.toedter.calendar.JDateChooser();
        calendarioHasta = new com.toedter.calendar.JDateChooser();
        botonBuscar = new javax.swing.JButton();
        campoProd = new javax.swing.JTextField();
        labelProd = new javax.swing.JLabel();
        labelProxDep = new javax.swing.JLabel();
        campoDep = new javax.swing.JTextField();
        botoncalcularDep = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(903, 581));

        tablaEstadisticas.setBackground(new java.awt.Color(254, 254, 254));
        tablaEstadisticas.setName("Estadisticas"); // NOI18N

        tablaEst.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod.Producto", "Nombre", "Cant. vendidos", "Ganancia", "Perdida", "Prom.Cant.Vendidos", "Prom.Ventas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaEstadisticas.setViewportView(tablaEst);

        labelDia.setText("Dia");

        labelDesde.setText("Desde");

        labelHasta.setText("Hasta");

        campoDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDiaActionPerformed(evt);
            }
        });

        calendarioDesde.setDateFormatString("yyyy-MM-dd");

        calendarioHasta.setDateFormatString("yyyy-MM-dd");

        botonBuscar.setText("Calcular");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        campoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoProdActionPerformed(evt);
            }
        });

        labelProd.setText("Cod.Producto");

        labelProxDep.setText("Proximo Deposito");

        campoDep.setEditable(false);

        botoncalcularDep.setText("Calcular");
        botoncalcularDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncalcularDepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tablaEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 1016, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelDesde)
                                            .addComponent(labelHasta)
                                            .addComponent(labelDia)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(labelProd)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoDia, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(calendarioDesde, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(calendarioHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(campoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelProxDep)
                        .addGap(33, 33, 33)
                        .addComponent(campoDep, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(botoncalcularDep)
                        .addGap(96, 96, 96)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelProd))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDia)
                    .addComponent(campoDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelProxDep)
                    .addComponent(campoDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botoncalcularDep))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDesde)
                    .addComponent(calendarioDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelHasta)
                    .addComponent(calendarioHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(botonBuscar)
                .addGap(30, 30, 30)
                .addComponent(tablaEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoProdActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void campoDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDiaActionPerformed

    private void botoncalcularDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncalcularDepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botoncalcularDepActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botoncalcularDep;
    private com.toedter.calendar.JDateChooser calendarioDesde;
    private com.toedter.calendar.JDateChooser calendarioHasta;
    private javax.swing.JTextField campoDep;
    private javax.swing.JTextField campoDia;
    private javax.swing.JTextField campoProd;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDesde;
    private javax.swing.JLabel labelDia;
    private javax.swing.JLabel labelHasta;
    private javax.swing.JLabel labelProd;
    private javax.swing.JLabel labelProxDep;
    private javax.swing.JTable tablaEst;
    private javax.swing.JScrollPane tablaEstadisticas;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the calendarioDesde
     */
    public com.toedter.calendar.JDateChooser getCalendarioDesde() {
        return calendarioDesde;
    }

    /**
     * @param calendarioDesde the calendarioDesde to set
     */
    public void setCalendarioDesde(com.toedter.calendar.JDateChooser calendarioDesde) {
        this.calendarioDesde = calendarioDesde;
    }

    /**
     * @return the calendarioHasta
     */
    public com.toedter.calendar.JDateChooser getCalendarioHasta() {
        return calendarioHasta;
    }

    /**
     * @param calendarioHasta the calendarioHasta to set
     */
    public void setCalendarioHasta(com.toedter.calendar.JDateChooser calendarioHasta) {
        this.calendarioHasta = calendarioHasta;
    }

    /**
     * @return the campoDia
     */
    public javax.swing.JTextField getCampoDia() {
        return campoDia;
    }

    /**
     * @param campoDia the campoDia to set
     */
    public void setCampoDia(javax.swing.JTextField campoDia) {
        this.campoDia = campoDia;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * @return the labelDesde
     */
    public javax.swing.JLabel getLabelDesde() {
        return labelDesde;
    }

    /**
     * @param labelDesde the labelDesde to set
     */
    public void setLabelDesde(javax.swing.JLabel labelDesde) {
        this.labelDesde = labelDesde;
    }

    /**
     * @return the labelDia
     */
    public javax.swing.JLabel getLabelDia() {
        return labelDia;
    }

    /**
     * @param labelDia the labelDia to set
     */
    public void setLabelDia(javax.swing.JLabel labelDia) {
        this.labelDia = labelDia;
    }

    /**
     * @return the labelHasta
     */
    public javax.swing.JLabel getLabelHasta() {
        return labelHasta;
    }

    /**
     * @param labelHasta the labelHasta to set
     */
    public void setLabelHasta(javax.swing.JLabel labelHasta) {
        this.labelHasta = labelHasta;
    }

    /**
     * @return the tablaEst
     */
    public javax.swing.JTable getTablaEst() {
        return tablaEst;
    }

    /**
     * @param tablaEst the tablaEst to set
     */
    public void setTablaEst(javax.swing.JTable tablaEst) {
        this.tablaEst = tablaEst;
    }

    /**
     * @return the tablaEstadisticas
     */
    public javax.swing.JScrollPane getTablaEstadisticas() {
        return tablaEstadisticas;
    }

    /**
     * @param tablaEstadisticas the tablaEstadisticas to set
     */
    public void setTablaEstadisticas(javax.swing.JScrollPane tablaEstadisticas) {
        this.tablaEstadisticas = tablaEstadisticas;
    }

    /**
     * @return the tablaEstDef
     */
    public DefaultTableModel getTablaEstDef() {
        return tablaEstDef;
    }

    /**
     * @param tablaEstDef the tablaEstDef to set
     */
    public void setTablaEstDef(DefaultTableModel tablaEstDef) {
        this.tablaEstDef = tablaEstDef;
    }

    /**
     * @return the botonBuscar
     */
    public javax.swing.JButton getBotonBuscar() {
        return botonBuscar;
    }

    /**
     * @param botonBuscar the botonBuscar to set
     */
    public void setBotonBuscar(javax.swing.JButton botonBuscar) {
        this.botonBuscar = botonBuscar;
    }

    /**
     * @return the campoProd
     */
    public javax.swing.JTextField getCampoProd() {
        return campoProd;
    }

    /**
     * @param campoProd the campoProd to set
     */
    public void setCampoProd(javax.swing.JTextField campoProd) {
        this.campoProd = campoProd;
    }

    /**
     * @return the labelProd
     */
    public javax.swing.JLabel getLabelProd() {
        return labelProd;
    }

    /**
     * @param labelProd the labelProd to set
     */
    public void setLabelProd(javax.swing.JLabel labelProd) {
        this.labelProd = labelProd;
    }

 

    /**
     * @return the botoncalcularDep
     */
    public javax.swing.JButton getBotoncalcularDep() {
        return botoncalcularDep;
    }

    /**
     * @param botoncalcularDep the botoncalcularDep to set
     */
    public void setBotoncalcularDep(javax.swing.JButton botoncalcularDep) {
        this.botoncalcularDep = botoncalcularDep;
    }

    /**
     * @return the campoDep
     */
    public javax.swing.JTextField getCampoDep() {
        return campoDep;
    }

    /**
     * @param campoDep the campoDep to set
     */
    public void setCampoDep(javax.swing.JTextField campoDep) {
        this.campoDep = campoDep;
    }

 

 
    
}
