/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.event.ActionEvent;
import javax.swing.JPanel;

/**
 *
 * @author joako
 */
public class MainGUI extends javax.swing.JFrame {
    
    private CajaGUI caja;
    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        caja = new CajaGUI();
        caja.disableAll();
        tab.add("Caja",caja);
        tab.setToolTipTextAt(0, "Manejo de la Caja Diaria");

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab = new javax.swing.JTabbedPane();
        barraMenu = new javax.swing.JMenuBar();
        archivo = new javax.swing.JMenu();
        abrirCaja = new javax.swing.JMenuItem();
        cerrarCaja = new javax.swing.JMenuItem();
        cuenta = new javax.swing.JMenu();
        producto = new javax.swing.JMenu();
        ventanaProductos = new javax.swing.JMenuItem();
        ayuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        archivo.setText("Archivo");

        abrirCaja.setText("Abrir Caja");
        abrirCaja.setToolTipText("Abre una caja para empezar a registrar transacciones.");
        archivo.add(abrirCaja);

        cerrarCaja.setText("Cerrar e Imprimir");
        archivo.add(cerrarCaja);

        barraMenu.add(archivo);

        cuenta.setText("Cuenta");
        barraMenu.add(cuenta);

        producto.setText("Producto");

        ventanaProductos.setText("Abrir ventana de productos");
        ventanaProductos.setActionCommand("VentanaProductos");
        producto.add(ventanaProductos);

        barraMenu.add(producto);

        ayuda.setText("Ayuda");
        barraMenu.add(ayuda);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrirCaja;
    private javax.swing.JMenu archivo;
    private javax.swing.JMenu ayuda;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem cerrarCaja;
    private javax.swing.JMenu cuenta;
    private javax.swing.JMenu producto;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JMenuItem ventanaProductos;
    // End of variables declaration//GEN-END:variables

    public CajaGUI getCaja(){
        return caja;
    }

    /**
     * @return the abrirCaja
     */
    public javax.swing.JMenuItem getAbrirCaja() {
        return abrirCaja;
    }

    /**
     * @return the archivo
     */
    public javax.swing.JMenu getArchivo() {
        return archivo;
    }

    /**
     * @return the ayuda
     */
    public javax.swing.JMenu getAyuda() {
        return ayuda;
    }

    /**
     * @return the cerrarCaja
     */
    public javax.swing.JMenuItem getCerrarCaja() {
        return cerrarCaja;
    }

    /**
     * @return the producto
     */
    public javax.swing.JMenu getProducto() {
        return producto;
    }

    /**
     * @return the ventanaProductos
     */
    public javax.swing.JMenuItem getVentanaProductos() {
        return ventanaProductos;
    }
}
